name: soda_dq_check
description: ''
version: 0.0.1
author: shashank@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: sodadqcheck
  parentArtefactID: shashankprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-08-27 07:25:21'
pipelines:
  pipelines/soda_dq:
    name: soda_dq
    description: ''
    author: shashank@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-27 07:25:21'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/data_generator:
    name: data_generator
    description: ''
    author: shashank@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-28 10:02:36'
    datasets:
      inputs:
      - datasets/data_generator
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pydeequ_data_quality_check:
    name: pydeequ_data_quality_check
    description: ''
    author: shashank@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-28 10:04:01'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/Customers:
    name: Customers
    description: ''
    author: shashank@prophecy.io
    createdAt: '2024-08-28 05:56:27'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2512
        datasetType: File
        description: ''
        author: shashank@prophecy.io
        createdAt: '2024-08-28 05:56:27'
  datasets/data_generator:
    name: data_generator
    description: ''
    author: shashank@prophecy.io
    createdAt: '2024-08-28 10:56:35'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2512
        datasetType: File
        description: ''
        author: shashank@prophecy.io
        createdAt: '2024-08-28 10:56:35'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/SodaDataQualityCheck:
      name: SodaDataQualityCheck
      category: Transform
      subCategory: ''
      description: null
      author: shashank@prophecy.io
      mode: batch
      files:
      - shashankprophecyioteam_sodadqcheck/gems/SodaDataQualityCheck.py
      gemType: ComponentGem
      dependencies: null
      createdAt: '2024-08-27 07:25:57'
    gems/dataQualtiyCheck:
      name: dataQualtiyCheck
      category: Transform
      subCategory: ''
      description: null
      author: shashank@prophecy.io
      mode: batch
      files:
      - shashankprophecyioteam_sodadqcheck/gems/dataQualityCheck.py
      gemType: ComponentGem
      dependencies: []
      createdAt: '2024-08-28 10:04:52'
    gems/SyntheticDataGenerator:
      name: SyntheticDataGenerator
      category: Source/Target
      subCategory: File
      description: null
      author: shashank@prophecy.io
      mode: batch
      files:
      - shashankprophecyioteam_sodadqcheck/gems/SyntheticDataGenerator.py
      gemType: DatasetGem
      dependencies: null
      createdAt: '2024-08-28 10:53:34'
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-27 07:25:21'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-08-28T10:04:05.131833Z'
  name: plibMaven
  version: 8.1.4
  id: '54527070'
  createdAt: '2024-08-28T10:04:05.131746Z'
- type: plibPypi
  modifiedAt: '2024-08-28T10:04:05.131891Z'
  name: plibPypi
  version: 1.9.14
  id: '943514664'
  createdAt: '2024-08-28T10:04:05.131872Z'
projectDependencies:
  '42':
    projectUID: 42
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_42.git&subPath=
    version: 0.2.27.dev3
    isDefault: true
    author: null
    createdAt: '2024-08-27 07:22:46'
  '43':
    projectUID: 43
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_43.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-08-27 07:22:46'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
