name: first_project
description: ''
version: 0.0.1
author: abhinav+demo@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: first_project
  parentArtefactID: abhinavdemoprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-09-12 13:22:36'
pipelines:
  pipelines/first_pipeline:
    name: first_pipeline
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-12 13:22:36'
    datasets:
      inputs:
      - datasets/asd
      - datasets/new_kafka
      outputs:
      - datasets/write_kafka
    subgraphs: []
    dependencies: {}
datasets:
  datasets/asd:
    name: asd
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-07-24 11:31:52'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-07-24 11:31:52'
  datasets/new_kafka:
    name: new_kafka
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-07-24 11:43:46'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-07-24 11:43:46'
  datasets/asfdasf:
    name: asfdasf
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-07-24 13:13:50'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: Warehouse
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-07-24 13:13:50'
  datasets/write_kafka:
    name: write_kafka
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-07-31 21:33:36'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-07-31 21:33:36'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/avro:
      name: avro
      category: Source/Target
      subCategory: File
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - abhinavdemoprophecyio_team_first_project/gems/AvroFormat.py
      gemType: DatasetGem
      dependencies: []
      createdAt: '2024-07-25 20:22:04'
    gems/KafkaStream:
      name: KafkaStream
      category: Source/Target
      subCategory: File
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - abhinavdemoprophecyio_team_first_project/gems/KafkaStream.py
      gemType: DatasetGem
      dependencies: null
      createdAt: '2024-07-31 20:28:35'
    gems/redshift:
      name: redshift
      category: Source/Target
      subCategory: Warehouse
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - abhinavdemoprophecyio_team_first_project/gems/redshift.py
      gemType: DatasetGem
      dependencies: []
      createdAt: '2024-08-09 07:07:19'
  dependencies: null
functions:
  author: null
  createdAt: '2023-09-12 13:22:36'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules:
    businessRules/new_rule:
      name: new_rule
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: abhinav+demo@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-07-24T09:30:21.898428Z'
  name: plibMaven
  version: 8.0.29
  id: '2082112976'
  createdAt: '2024-07-24T09:30:21.898378Z'
- type: plibPypi
  modifiedAt: '2024-07-24T09:30:21.898496Z'
  name: plibPypi
  version: 1.9.9
  id: '1921516960'
  createdAt: '2024-07-24T09:30:21.898484Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.26
    isDefault: true
    author: null
    createdAt: '2024-08-26 13:14:13'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-24 09:30:23'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
