name: first_project
description: ''
version: 0.0.1
author: abhinav+demo@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: first_project
  parentArtefactID: abhinavdemoprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-09-12 13:22:36'
pipelines:
  pipelines/employee_heirarchy:
    name: employee_heirarchy
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-03-19 07:48:34'
    datasets:
      inputs:
      - datasets/employee
      outputs:
      - datasets/employee_heirarchy
    subgraphs: []
    dependencies: {}
  pipelines/fetch_config_from_metadata:
    name: fetch_config_from_metadata
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-03-19 07:50:29'
    datasets:
      inputs:
      - datasets/metadata_date_filter
      outputs:
      - datasets/metadata_date_filter_output_dummy
    subgraphs: []
    dependencies: {}
  pipelines/gold_layer_snapshot:
    name: gold_layer_snapshot
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-03-19 10:19:06'
    datasets:
      inputs:
      - datasets/db1_orders
      - datasets/db2_orders
      - datasets/orders_latest
      - datasets/orders_snapshot
      - datasets/orders_threshold
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/employee:
    name: employee
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-18 11:53:08'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-18 11:53:08'
  datasets/employee_heirarchy:
    name: employee_heirarchy
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 07:11:12'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 07:11:12'
  datasets/metadata_date_filter:
    name: metadata_date_filter
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 07:55:12'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 07:55:12'
  datasets/metadata_date_filter_output_dummy:
    name: metadata_date_filter_output_dummy
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 08:17:16'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 08:17:16'
  datasets/db1_orders:
    name: db1_orders
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 10:01:18'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 10:01:18'
  datasets/db2_orders:
    name: db2_orders
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 10:01:48'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 10:01:48'
  datasets/configurable_orders:
    name: configurable_orders
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 10:02:55'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 10:02:55'
  datasets/orders_metadata:
    name: orders_metadata
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 10:09:12'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 10:09:12'
  datasets/orders_threshold:
    name: orders_threshold
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 10:26:49'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 10:26:49'
  datasets/orders_snapshot:
    name: orders_snapshot
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 10:27:40'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 10:27:40'
  datasets/orders_latest:
    name: orders_latest
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 10:37:12'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 10:37:12'
  datasets/new_dataset:
    name: new_dataset
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 12:36:20'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 12:36:20'
  datasets/abhinav_demo_employees:
    name: abhinav_demo_employees
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 12:37:18'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 12:37:18'
  datasets/abhinav_demo_cust_ord_demo1:
    name: abhinav_demo_cust_ord_demo1
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2025-03-19 12:49:20'
    mode: batch
    physicalDatasets:
      non_unity_fabric:
        fabricId: 2122
        datasetType: Database
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2025-03-19 12:49:20'
templates: {}
jobs:
  jobs/fetch_config_from_metadata:
    name: fetch_config_from_metadata
    description: ''
    fabricUID: 2122
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/fetch_config_from_metadata
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2025-03-19 08:27:04'
    author: abhinav+demo@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/catalogTable:
      name: catalogTable
      category: Source/Target
      subCategory: Database
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - abhinavdemoprophecyio_team_first_project/gems/catalogTable.py
      gemType: DatasetGem
      dependencies: []
      createdAt: '2025-03-19 10:41:10'
    gems/RowDistributor:
      name: RowDistributor
      category: Join/Split
      subCategory: ''
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - abhinavdemoprophecyio_team_first_project/gems/RowDistributor.py
      gemType: ComponentGem
      dependencies: null
      createdAt: '2025-03-19 12:53:48'
  dependencies: null
functions:
  author: null
  createdAt: '2023-09-12 13:22:36'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-07-24T09:30:21.898428Z'
  name: plibMaven
  version: 8.8.2
  id: '2082112976'
  createdAt: '2024-07-24T09:30:21.898378Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2025-01-30T08:51:32.917Z'
  name: ProphecyLibsPython
  version: 1.9.36
  id: '1921516960'
  createdAt: '2024-07-24T09:30:21.898484Z'
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.40
    isDefault: true
    author: null
    createdAt: '2025-03-18 11:49:54'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-24 09:30:23'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
