name: custom_gem_demos_new
description: ''
version: '0.1'
author: abhinav+demo@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: customgemdemosnew
  parentArtefactID: demoteamabhinav
  buildSystem: wheel
  author: null
  createdAt: '2024-07-21 07:30:16'
pipelines:
  pipelines/gem_testing:
    name: gem_testing
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-21 07:30:16'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/SchemaTransform:
      name: SchemaTransform
      category: Transform
      subCategory: ''
      description: null
      author: abhinav+demo@prophecy.io
      mode: batch
      files:
      - demoteamabhinav_customgemdemosnew/gems/SchemaTransform.py
      gemType: ComponentGem
      dependencies: null
      createdAt: '2024-07-21 07:33:27'
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-21 07:30:16'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-07-21T07:30:16.129693Z'
  name: plibMaven
  version: 8.0.25
  id: '848385427'
  createdAt: '2024-07-21T07:30:16.129693Z'
  type: plibMaven
- modifiedAt: '2024-07-21T07:30:16.129693Z'
  name: plibPypi
  version: 1.9.9
  id: '1875097243'
  createdAt: '2024-07-21T07:30:16.129693Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-21 07:29:17'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-21 07:29:17'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
