name: custom_gem_demos
description: ''
version: '0.5'
author: abhinav+gems@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: customgemdemos
  parentArtefactID: gemadmin
  buildSystem: wheel
  author: null
  createdAt: '2023-10-12 14:00:06'
pipelines:
  pipelines/gem_testing:
    name: gem_testing
    description: ''
    author: abhinav+gems@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-12 14:00:06'
    datasets:
      inputs:
      - datasets/customers
      - datasets/deleted_customers
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customers:
    name: customers
    description: ''
    author: abhinav+gems@prophecy.io
    createdAt: '2023-10-12 14:48:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 5694
        datasetType: File
        description: ''
        author: abhinav+gems@prophecy.io
        createdAt: '2023-10-12 14:48:31'
  datasets/deleted_customers:
    name: deleted_customers
    description: ''
    author: abhinav+gems@prophecy.io
    createdAt: '2023-10-12 17:40:32'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 5694
        datasetType: File
        description: ''
        author: abhinav+gems@prophecy.io
        createdAt: '2023-10-12 17:40:32'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/Masking:
      name: Masking
      category: Transform
      subCategory: ''
      description: null
      author: abhinav+gems@prophecy.io
      mode: batch
      files:
      - gemadmin_customgemdemos/gems/Masking.py
      createdAt: '2023-10-12 14:00:57'
    gems/Limit:
      name: Limit
      category: Transform
      subCategory: ''
      description: null
      author: abhinav+gems@prophecy.io
      mode: batch
      files:
      - gemadmin_customgemdemos/gems/Limit.py
      createdAt: '2023-10-12 18:03:26'
functions:
  author: null
  createdAt: '2023-10-12 14:00:06'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.4
    isDefault: true
    author: null
    createdAt: '2023-10-12 13:59:48'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-10-12 13:59:48'
pipelineConfigurations: {}
