name: git_demo
description: ''
version: '0.1'
author: ''
language: python
buildSystem: wheel
pipelines:
  pipelines/first_pipeline:
    name: first_pipeline
    description: ''
    author: abhinav+1@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-06-20 07:00:16'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
dependencies: '[]'
