name: co_pilot_demo
description: ''
version: 0.0.1
author: abhinav+demo@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: copilotdemo
  parentArtefactID: abhinavdemoprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-09-11 13:19:26'
pipelines:
  pipelines/customer_orders:
    name: customer_orders
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-09-11 13:19:56'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/demo_pipeline:
    name: demo_pipeline
    description: ''
    author: abhinav+demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-09-11 13:21:51'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customers:
    name: customers
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-09-11 13:20:48'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-09-11 13:20:48'
  datasets/orders:
    name: orders
    description: ''
    author: abhinav+demo@prophecy.io
    createdAt: '2024-09-11 13:21:24'
    mode: batch
    physicalDatasets:
      unity_fabric:
        fabricId: 2121
        datasetType: File
        description: ''
        author: abhinav+demo@prophecy.io
        createdAt: '2024-09-11 13:21:24'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-09-11 13:19:26'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-09-11T13:19:26.314092Z'
  name: plibMaven
  version: 8.1.4
  id: '1117056051'
  createdAt: '2024-09-11T13:19:26.314092Z'
  type: plibMaven
  enabled: true
  entity: Project
- modifiedAt: '2024-09-11T13:19:44.970Z'
  name: ProphecyLibsPython
  version: 1.9.14
  id: '89850046'
  createdAt: '2024-09-11T13:19:26.314092Z'
  type: plibPypi
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.28
    isDefault: true
    author: null
    createdAt: '2024-09-11 13:19:11'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-09-11 13:19:11'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
