from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from employee_heirarchy.config.ConfigStore import *
from employee_heirarchy.functions import *

def reformatted_hierarchy_data(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("AUX_SRC_SYS"), 
        col("AUX_INS_DTM"), 
        col("AUX_SRC_STATUS"), 
        col("POS_NUM"), 
        col("POS_TITLE"), 
        col("EM_POS_NUM"), 
        col("HEIRARCHY_ARR")[0].getField("POS_NUM").alias("LEVEL_0_POS_NUM"), 
        col("HEIRARCHY_ARR")[0].getField("POS_TITLE").alias("LEVEL_0_POS_TITLE"), 
        col("HEIRARCHY_ARR")[0].getField("EMPL_ID").alias("LEVEL_0_EMPL_ID"), 
        col("HEIRARCHY_ARR")[0].getField("EMPL_NAME").alias("LEVEL_0_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[1].getField("POS_NUM").alias("LEVEL_1_POS_NUM"), 
        col("HEIRARCHY_ARR")[1].getField("POS_TITLE").alias("LEVEL_1_POS_TITLE"), 
        col("HEIRARCHY_ARR")[1].getField("EMPL_ID").alias("LEVEL_1_EMPL_ID"), 
        col("HEIRARCHY_ARR")[1].getField("EMPL_NAME").alias("LEVEL_1_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[2].getField("POS_NUM").alias("LEVEL_2_POS_NUM"), 
        col("HEIRARCHY_ARR")[2].getField("POS_TITLE").alias("LEVEL_2_POS_TITLE"), 
        col("HEIRARCHY_ARR")[2].getField("EMPL_ID").alias("LEVEL_2_EMPL_ID"), 
        col("HEIRARCHY_ARR")[2].getField("EMPL_NAME").alias("LEVEL_2_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[3].getField("POS_NUM").alias("LEVEL_3_POS_NUM"), 
        col("HEIRARCHY_ARR")[3].getField("POS_TITLE").alias("LEVEL_3_POS_TITLE"), 
        col("HEIRARCHY_ARR")[3].getField("EMPL_ID").alias("LEVEL_3_EMPL_ID"), 
        col("HEIRARCHY_ARR")[3].getField("EMPL_NAME").alias("LEVEL_3_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[4].getField("POS_NUM").alias("LEVEL_4_POS_NUM"), 
        col("HEIRARCHY_ARR")[4].getField("POS_TITLE").alias("LEVEL_4_POS_TITLE"), 
        col("HEIRARCHY_ARR")[4].getField("EMPL_ID").alias("LEVEL_4_EMPL_ID"), 
        col("HEIRARCHY_ARR")[4].getField("EMPL_NAME").alias("LEVEL_4_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[5].getField("POS_NUM").alias("LEVEL_5_POS_NUM"), 
        col("HEIRARCHY_ARR")[5].getField("POS_TITLE").alias("LEVEL_5_POS_TITLE"), 
        col("HEIRARCHY_ARR")[5].getField("EMPL_ID").alias("LEVEL_5_EMPL_ID"), 
        col("HEIRARCHY_ARR")[5].getField("EMPL_NAME").alias("LEVEL_5_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[6].getField("POS_NUM").alias("LEVEL_6_POS_NUM"), 
        col("HEIRARCHY_ARR")[6].getField("POS_TITLE").alias("LEVEL_6_POS_TITLE"), 
        col("HEIRARCHY_ARR")[6].getField("EMPL_ID").alias("LEVEL_6_EMPL_ID"), 
        col("HEIRARCHY_ARR")[6].getField("EMPL_NAME").alias("LEVEL_6_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[7].getField("POS_NUM").alias("LEVEL_7_POS_NUM"), 
        col("HEIRARCHY_ARR")[7].getField("POS_TITLE").alias("LEVEL_7_POS_TITLE"), 
        col("HEIRARCHY_ARR")[7].getField("EMPL_ID").alias("LEVEL_7_EMPL_ID"), 
        col("HEIRARCHY_ARR")[7].getField("EMPL_NAME").alias("LEVEL_7_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[8].getField("POS_NUM").alias("LEVEL_8_POS_NUM"), 
        col("HEIRARCHY_ARR")[8].getField("POS_TITLE").alias("LEVEL_8_POS_TITLE"), 
        col("HEIRARCHY_ARR")[8].getField("EMPL_ID").alias("LEVEL_8_EMPL_ID"), 
        col("HEIRARCHY_ARR")[8].getField("EMPL_NAME").alias("LEVEL_8_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[9].getField("POS_NUM").alias("LEVEL_9_POS_NUM"), 
        col("HEIRARCHY_ARR")[9].getField("POS_TITLE").alias("LEVEL_9_POS_TITLE"), 
        col("HEIRARCHY_ARR")[9].getField("EMPL_ID").alias("LEVEL_9_EMPL_ID"), 
        col("HEIRARCHY_ARR")[9].getField("EMPL_NAME").alias("LEVEL_9_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[10].getField("POS_NUM").alias("LEVEL_10_POS_NUM"), 
        col("HEIRARCHY_ARR")[10].getField("POS_TITLE").alias("LEVEL_10_POS_TITLE"), 
        col("HEIRARCHY_ARR")[10].getField("EMPL_ID").alias("LEVEL_10_EMPL_ID"), 
        col("HEIRARCHY_ARR")[10].getField("EMPL_NAME").alias("LEVEL_10_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[11].getField("POS_NUM").alias("LEVEL_11_POS_NUM"), 
        col("HEIRARCHY_ARR")[11].getField("POS_TITLE").alias("LEVEL_11_POS_TITLE"), 
        col("HEIRARCHY_ARR")[11].getField("EMPL_ID").alias("LEVEL_11_EMPL_ID"), 
        col("HEIRARCHY_ARR")[11].getField("EMPL_NAME").alias("LEVEL_11_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[12].getField("POS_NUM").alias("LEVEL_12_POS_NUM"), 
        col("HEIRARCHY_ARR")[12].getField("POS_TITLE").alias("LEVEL_12_POS_TITLE"), 
        col("HEIRARCHY_ARR")[12].getField("EMPL_ID").alias("LEVEL_12_EMPL_ID"), 
        col("HEIRARCHY_ARR")[12].getField("EMPL_NAME").alias("LEVEL_12_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[13].getField("POS_NUM").alias("LEVEL_13_POS_NUM"), 
        col("HEIRARCHY_ARR")[13].getField("POS_TITLE").alias("LEVEL_13_POS_TITLE"), 
        col("HEIRARCHY_ARR")[13].getField("EMPL_ID").alias("LEVEL_13_EMPL_ID"), 
        col("HEIRARCHY_ARR")[13].getField("EMPL_NAME").alias("LEVEL_13_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[14].getField("POS_NUM").alias("LEVEL_14_POS_NUM"), 
        col("HEIRARCHY_ARR")[14].getField("POS_TITLE").alias("LEVEL_14_POS_TITLE"), 
        col("HEIRARCHY_ARR")[14].getField("EMPL_ID").alias("LEVEL_14_EMPL_ID"), 
        col("HEIRARCHY_ARR")[14].getField("EMPL_NAME").alias("LEVEL_14_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[15].getField("POS_NUM").alias("LEVEL_15_POS_NUM"), 
        col("HEIRARCHY_ARR")[15].getField("POS_TITLE").alias("LEVEL_15_POS_TITLE"), 
        col("HEIRARCHY_ARR")[15].getField("EMPL_ID").alias("LEVEL_15_EMPL_ID"), 
        col("HEIRARCHY_ARR")[15].getField("EMPL_NAME").alias("LEVEL_15_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[16].getField("POS_NUM").alias("LEVEL_16_POS_NUM"), 
        col("HEIRARCHY_ARR")[16].getField("POS_TITLE").alias("LEVEL_16_POS_TITLE"), 
        col("HEIRARCHY_ARR")[16].getField("EMPL_ID").alias("LEVEL_16_EMPL_ID"), 
        col("HEIRARCHY_ARR")[16].getField("EMPL_NAME").alias("LEVEL_16_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[17].getField("POS_NUM").alias("LEVEL_17_POS_NUM"), 
        col("HEIRARCHY_ARR")[17].getField("POS_TITLE").alias("LEVEL_17_POS_TITLE"), 
        col("HEIRARCHY_ARR")[17].getField("EMPL_ID").alias("LEVEL_17_EMPL_ID"), 
        col("HEIRARCHY_ARR")[17].getField("EMPL_NAME").alias("LEVEL_17_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[18].getField("POS_NUM").alias("LEVEL_18_POS_NUM"), 
        col("HEIRARCHY_ARR")[18].getField("POS_TITLE").alias("LEVEL_18_POS_TITLE"), 
        col("HEIRARCHY_ARR")[18].getField("EMPL_ID").alias("LEVEL_18_EMPL_ID"), 
        col("HEIRARCHY_ARR")[18].getField("EMPL_NAME").alias("LEVEL_18_EMPL_NAME"), 
        col("HEIRARCHY_ARR")[19].getField("POS_NUM").alias("LEVEL_19_POS_NUM"), 
        col("HEIRARCHY_ARR")[19].getField("POS_TITLE").alias("LEVEL_19_POS_TITLE"), 
        col("HEIRARCHY_ARR")[19].getField("EMPL_ID").alias("LEVEL_19_EMPL_ID"), 
        col("HEIRARCHY_ARR")[19].getField("EMPL_NAME").alias("LEVEL_19_EMPL_NAME"), 
        (size(col("HEIRARCHY_ARR")) - lit(1)).alias("LAYER")
    )
